### PR TITLE
handling of reHLT MC datasets

### PR DESCRIPTION
**Pull request by OlivierBondu**
goes along with https://github.com/cp3-llbb/Framework/pull/206 to address point 3. of https://github.com/cp3-llbb/Framework/issues/205

### CODE REVIEW

**Comment by blinkseb** [comment]
Looks good thanks! Did you test it?

**Comment by OlivierBondu** [comment]
not yet ;)

**Comment by OlivierBondu** [comment]
updated with small fixes, it does work :)
(`config.JobType.pyCfgParams = ['runOnData=0', 'era=25ns', 'hltProcessName=HLT2']` appears in the crab config file)

**Comment by blinkseb** [comment]
Perfect, thanks a lot!

**Pull request merged**
