### PR TITLE
Store the list of processed lumi sections for data

### PR DESCRIPTION
**Pull request by blinkseb**
This is useful to easily recompute the luminosity of a sample if/when the luminosity calibrations change.

This depends on https://github.com/cp3-llbb/SAMADhi/pull/5 and the database layout will need to be updated.

### CODE REVIEW

**Comment by blinkseb** [comment]
Database has been upgraded to the new layout. This is ready to go.

It would be great if someone can test this on data first (I only have MC) to see if it's working. The `llbb_test` database is also upgraded to the new schema.

**Comment by swertz** [comment]
I can do the test; where do I change the database to use llbb_test instead?

**Comment by OlivierBondu** [comment]
it's in `SAMADhi/scripts/SAMADhi.py` , + a `scram b` to link the correct python script in `CMSSW/bin`

**Comment by swertz** [comment]
Thanks. I'm having this:

```##### Get information out of the crab config file (work area, dataset, pset)
done

##### Check if the dataset exists in the database
calling das_import
****das query: [{u'dataset': [{u'datatype': u'data', u'tag': None, u'creation_time': u'2015-09-19 17:53:46', u'name': u'/DoubleMuon/Run2015D-PromptReco-v3/MINIAOD'}]}]
Traceback (most recent call last):
  File "/nfs/scratch/fynu/swertz/CMSSW_7_4_10/bin/slc6_amd64_gcc491/runPostCrab.py", line 319, in <module>
    main() 
  File "/nfs/scratch/fynu/swertz/CMSSW_7_4_10/bin/slc6_amd64_gcc491/runPostCrab.py", line 208, in main
    das_import.main()
  File "/nfs/scratch/fynu/swertz/CMSSW_7_4_10/bin/slc6_amd64_gcc491/das_import.py", line 281, in main
    dataset = asDataset(jsondict1[0]["dataset"][0])
  File "/nfs/scratch/fynu/swertz/CMSSW_7_4_10/bin/slc6_amd64_gcc491/das_import.py", line 215, in asDataset
    setattr(result,column,dct[key])
KeyError: u'size'
```

**Comment by swertz** [comment]
Tested and OK :)

**Pull request merged**
