### PR TITLE
Improvements to runPostCrab, fix #8

### LINKED ISSUE #8: Add sum(w) into the database

### PR DESCRIPTION
**Pull request by OlivierBondu**
- It is now possible to insert in the DB samples that were not 100% completed by crab, but this assumes crab has finished, and will erase from disk root files not known to crab.
  Hopefully, the warnings are big enough so that this won't be happening by mistake (two of them, each requiring action from the user)
  - A clean fix would need to add to the DB a 'list of files' field
- the sum(w) is now stored in the 'normalization' field
- stdout has been tidied up a bit and should contain more useful info on what is being done

### CODE REVIEW

**Comment by blinkseb** [comment]
Seems fine. I'm currently working on storing the list of input files into the database, so hopefully, we won't need to delete stuff for too long.

I'm waiting for others +1 before merging

**Comment by swertz** [comment]
Here's what I get when I try running it:

```
7 files have been processed
95285 events have been read
0 events have been written
Analyzed luminosity sections written to /nfs/scratch/fynu/swertz/CMSSW_7_4_10/src/cp3_llbb/GridIn/test/tasks/crab_MuonEG_Run2015C-PromptReco-v1_2015-09-04/results/lumiSummary.json
##### Check if the job processed the whole sample
##### Figure out the code(s) version
Traceback (most recent call last):
  File "/nfs/scratch/fynu/swertz/CMSSW_7_4_10/bin/slc6_amd64_gcc491/runPostCrab.py", line 226, in <module>
    main() 
  File "/nfs/scratch/fynu/swertz/CMSSW_7_4_10/bin/slc6_amd64_gcc491/runPostCrab.py", line 171, in main
    AnaHash, AnaBranch, AnaUrl = getGitTagBranchUrl( os.path.dirname( psetName ) )
  File "/nfs/scratch/fynu/swertz/CMSSW_7_4_10/bin/slc6_amd64_gcc491/runPostCrab.py", line 48, in getGitTagBranchUrl
    proc = subprocess.Popen(['git', 'remote', 'show', 'origin'], cwd = gitCallPath, stdout=subprocess.PIPE)
  File "/nfs/soft/python/python-2.7.5-sl6_amd64_gcc44/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/nfs/soft/python/python-2.7.5-sl6_amd64_gcc44/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: ''
```

**Comment by swertz** [comment]
Tested and Ok on my side

**Comment by blinkseb** [comment]
Why was it failing?

**Comment by swertz** [comment]
I had copied the CMSSW config file on which I was running to the GridIn/test directory, and so runPostCrab didn't find the corresponding git repo for the analyzer.

**Comment by OlivierBondu** [comment]
well, in the end there was 3 things:
- the bug above because the latest version of the script (with the correct access codes to the DB) was not in CMSSW/bin: should be avoided with the more explicit readme #23 (advising to re-run `scram b`)
- the CMSSW config file as mentionned, but "this is not a bug, it's a feature": you are not supposed to insert things in the database if they cannot be tracked
- the scary message was a bit too scary for data, given that when using a lumi mask you never run on all the existing files...

**Pull request merged**
