### PR TITLE
Update to latest golden json file for 2015D

### PR DESCRIPTION
**Pull request by BrieucF**

### CODE REVIEW

**Comment by swertz** [comment]
Thanks! But why not put the Silver?

**Comment by BrieucF** [comment]
Well, I think it is better if we keep the possibility to choose which one we want to run on. We could then duplicate the dataset.json to have one with the silver?

**Comment by blinkseb** [comment]
Or just use the '--lumi-mask' option of runOnGrid.py to override the json
file 😉
Le 27 nov. 2015 5:31 PM, "Brieuc Francois" notifications@github.com a
écrit :

**Comment by swertz** [comment]
If everyone uses the Silver maybe it's not worth the trouble to maintain two sets of JSONs? Especially if you guys decide to add SingleLepton datasets to boot...

**Comment by BrieucF** [comment]
Sorry, not sure I understood. You're saying that it is not a trouble to maintain the two json or the other way around? It is not clear yet to me whether we go for silver. During HW WS they were saying that nohfmet has a worse resolution and so proposed to do : "golden" with pfmet and "silver minus golden" with nohfmet (technically heavier).

**Comment by swertz** [comment]
Sorry, I updated my post ;) If you're not sure what to do then it's better to have both of course. On our side it was my understanding that using silver + noHFmet was fine.

**Comment by blinkseb** [comment]
It seems that we all agreed that using the silver json is not worth the trouble

**Comment by OlivierBondu** [comment]
:+1:

**Pull request merged**
